[project]
name = "pipelined-gpt-fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "transformers",
    "sentencepiece",
    "tiktoken",
    "blobfile",
    "dotenv>=0.9.9",
    "setuptools>=75.8.2",
    "torch>=2.6.0",
    "triton>=3.2.0",
    "maturin>=1.8.2",
    "loguru>=0.7.3",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = []

[dependency-groups]
dev = [
    "lovely-tensors>=0.1.18",
    "pytest>=8.3.5",
    "ruff>=0.9.10",
]
